# Generated by Django 4.2.16 on 2024-11-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citadel_Inicia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titles',
            new_name='title',
        ),
    ]
